# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=80)),
                ('amount', models.IntegerField(default=0)),
                ('date_awarded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housepoints.Category'),
        ),
        migrations.AddField(
            model_name='award',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housepoints.House'),
        ),
    ]
