# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housepoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FacStaffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('point_total', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('grade', models.IntegerField(default=3)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housepoints.House')),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housepoints.Category'),
        ),
        migrations.AlterField(
            model_name='award',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housepoints.Student'),
        ),
        migrations.AddField(
            model_name='facstaff',
            name='facstafftype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housepoints.FacStaffType'),
        ),
        migrations.AddField(
            model_name='facstaff',
            name='house_affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housepoints.House'),
        ),
        migrations.AddField(
            model_name='facstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
